# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'pim/akonadi-mime' : '@same'
    'pim/akonadi-contacts' : '@same'
    'pim/grantleetheme' : '@same'
    'pim/kimap' : '@same'
    'pim/kpimtextedit' : '@same'
    'pim/libkleo' : '@same'
    'pim/messagelib' : '@same'
    'pim/pimcommon' : '@same'
    'third-party/grantlee' : '@stable'
