# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'pim/akonadi-mime' : '@same'
    'pim/akonadi-contacts' : '@same'
    'pim/grantleetheme' : '@same'
    'pim/kimap' : '@same'
    'pim/kpimtextedit' : '@same'
    'pim/messagelib' : '@same'
    'pim/pimcommon' : '@same'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6']
  'require':
    'libraries/ktexttemplate': '@stable'

- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5']
  'require':
    'third-party/grantlee' : '@stable'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]      
